### PR TITLE
#74: SMTP client (closes #74)

### LINKED ISSUE #74: SMTP client
Create an SMTP implementation of MailClient trait

### PR DESCRIPTION
**Pull request by Cardu**
Closes #74

### tests performed

integration tests MailoSMTPSpec run with local SMTP server

### CODE REVIEW

**Comment by calippo** [comment]
false is not true

image

**Review by calippo — CHANGES_REQUESTED** [review]
false was not true

**Comment by Cardu** [comment]
@calippo I can't see why drone is still failing

**Comment by calippo** [comment]
All tests are passing but
```
[error] Expected symbol
[error] Not a valid command: -
[error] Expected end of input.
[error] Expected '--'
[error] Expected 'debug'
[error] Expected 'info'
[error] Expected 'warn'
[error] Expected 'error'
[error] Expected 'addPluginSbtFile'
[error] -Dsbt.ivy.home=/drone/.ivy
[error]  ^
[info] build failed (exit code 1)
```

**Comment by Cardu** [comment]
🤔  I don't think the error is related to this PR

**Pull request merged**
